on:
  check_run:
    types: [created, rerequested, completed]

jobs:
  scan:
   runs-on: ubuntu-latest
   steps:
     - name: security scan
       run: |
        echo 'Hello worldd'
        echo ${{ github.event.deployment.task }}
        echo ${{ github.event.deployment_status.state }}