name: Checkrun
on:
  check_run:
    types: [created, rerequested, completed]
  check_suite:
    types: [completed]
jobs:
  scan:
   runs-on: ubuntu-latest
   steps:
     - name: security scan
       run: |
        echo 'Hello worldd'