name: Rollout

name: "Repo dispatch"
on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    - uses: hmarr/debug-action@v2
    - name: Download artifacts
      run: |
        curl -o unity-renderer-windows.zip https://renderer-artifacts.decentraland.org/desktop/main/unity-renderer-windows.zip
        curl -o unity-renderer-mac.zip https://renderer-artifacts.decentraland.org/desktop/main/unity-renderer-mac.zip
        curl -o unity-renderer-linux.zip https://renderer-artifacts.decentraland.org/desktop/main/unity-renderer-linux.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          unity-renderer-windows.zip
          unity-renderer-mac.zip
          unity-renderer-linux.zip